version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - battledata:/var/www/html/game/battledata
      - battleresult:/var/www/html/game/battleresult
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ogame
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  battledata:
  battleresult:
